#!/usr/bin/env bash
IMAGE_NAME="edg956.github.io"
DEFAULT_RUN_CMD="docker run -it --rm --workdir /app/${IMAGE_NAME} -v `pwd`:/app"
build () {
	docker build . -t $IMAGE_NAME
}

shell() {
	$DEFAULT_RUN_CMD $IMAGE_NAME bash
}

start () {
	$DEFAULT_RUN_CMD -p 3000:3000 $IMAGE_NAME npm run dev		
}

install () {
	$DEFAULT_RUN_CMD $IMAGE_NAME npm run generate > /dev/null
	git checkout gh-pages > /dev/null
	cp -a dist/. .
	rm -r dist
	git add . > /dev/null
	git commit -m "Installed new version" > /dev/null
	git push > /dev/null
	git checkout master > /dev/null
}

ensure_deps () {
	$DEFAULT_RUN_CMD -u=$(id -u $(whoami)) $IMAGE_NAME npm install
}

case $1 in
	build)
		build
		;;
	start)
		start
		;;
	install)
		install
		;;
	shell)
		shell
		;;
	ensure_deps)
		ensure_deps
		;;
	*)
		echo "Unknown command"
		;;
esac
